[package]
name = "cypher-rs"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive", "cargo"] }
openssl = { version = "0.10.71", features = ["vendored"] }
serde = "1.0.219"
serde_derive = "1.0.219"
serde_yaml = "0.9.34"
