a: "α"
b: "β"
c: "γ"
d: "δ"
e: "ε"
f: "ζ"
g: "η"
h: "θ"
i: "ι"
j: "κ"
k: "λ"
l: "μ"
m: "ν"
n: "ξ"
o: "ο"
p: "π"
q: "ρ"
r: "σ"
s: "τ"
t: "υ"
u: "φ"
v: "χ"
w: "ψ"
x: "ω"
y: "й"
z: "æ"
A: "Λ"
B: "ℵ"
C: "Θ"
D: "ワ"
E: "∅"
F: "∴"
G: "∧"
H: "ç"
I: "γ"
J: "ば"
K: "‡"
L: "へ"
M: "þ"
N: "∨"
O: "∧"
P: "∅"
Q: "∴"
R: "∧"
S: "∅"
T: "∴"
U: "∧"
V: "∅"
W: "∴"
X: "∧"
Y: "∅"
Z: "∴"
